// Parcel references the Rust crate by importing its Cargo.toml file,
// but TypeScript can't resolve the import or access any of the types
// generated by wasm-bindgen.
//
// As a workaround:
//
// 1) We define this module declaration, which uses wildcard module
//    declarations (aka TypeScript's way of supporting non-JS loaders)
//    and uses `typeof` to get the real types produced by wasm-bindgen
//    https://github.com/rustwasm/wasm-bindgen/issues/182#issuecomment-487928242
//
// 2) We need to import this `index.d.ts` file at the top of `index.ts`
//    /// <reference path="./index.d.ts" />
//    I hope to God I don't have to do this in every file smh
declare module "*.toml" {
    const value: typeof import("../crate/pkg/raidtomi")
    export default value
}
